version: 2.1

build-template: &build-template
  docker:
    - image: soadmin/node
  steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Output env info
        command: node --version && yarn --version
    - run:
        name: Pull dependencies
        command: yarn
    - run:
        no_output_timeout: 10m
        name: Building ...
        command: yarn build
    - run: 
       name: Upload dist
       command: aws s3 cp ./build s3://$BUCKET_NAME/ --acl bucket-owner-full-control --recursive --cache-control "public,max-age=600,s-maxage=3600"
    - run:
        name: Cloudfront invalidation
        command: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths '/*'
        
jobs:
  # build
  build-main:
    <<: *build-template

workflows:
  version: 2.1
  test:
    jobs:
      # swap main
      - approve-main:
          type: approval
          filters:
            branches:
              only: [ main ]
      - build-main:
          context:
            - swap_cicd
            - swap_build_main
          requires:
            - approve-main
